const numero1 = 5;
const numero2 = 4



try {
    console.log(numero1);
    console.log(numero3);
    console.log(numero2);

} catch (error) {
    console.log(error);

}